apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  namespace: arun
  labels:
    app: arun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arun
  template:
    metadata:
      labels:
        app: arun
    spec:
      containers:
        - name: dotnet
          image: aaaaruuunnn.azurecr.io/dotnetdemo-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: arunbachi
