apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  namespace: arun
  labels:
    app: arun
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arun
  template:
    metadata:
      labels:
        app: arun
    spec:
      containers:
        - name: dotnet
          image: redbull.azurecr.io/1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: arun
